<a href="https://colab.research.google.com/github/KuriharaYoshiki/python_medical_images/blob/master/paspale.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pythonプログラムの基本を学ぶ。


### 2.1 データ型


2.1.1

In [0]:
print(type(10))

<class 'int'>


2.1.2

In [0]:
print(type("foo"))

<class 'str'>


2.1.3

In [0]:
print(type(-5))    # 整数
print(type(2.73))  # 浮動小数点
print(type(-5.0))


<class 'int'>
<class 'float'>
<class 'float'>


2.1.4

In [0]:
print(type(5+4+10))
print(type(5+4.0+10))
print(type(4.3/2))
print(type(4/2))
print(type(5//2))
print(type(5%2))

<class 'int'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'int'>
<class 'int'>


2.1.5

In [0]:
print(5+4+10)
print(5+4.0+10)
print(4.3/2)
print(4/2)
print(5//2)

19
19.0
2.15
2.0
2


2.1.6

In [0]:
print(5/2)
print(6.3/2)
print(8/3.0)

2.5
3.15
2.6666666666666665


2.1.7

In [0]:
print(5//2)
print(6.3//2)
print(8//3.0)

2
3.0
2.0


2.1.8

In [0]:
print(type("foo"))
print(type('foo'))
print(type("""hogehoge
fugafuga
barbar
booboo"""))

<class 'str'>
<class 'str'>
<class 'str'>


2.1.9

In [0]:
print("Alice"+" in "+"Wonderland")

Alice in Wonderland


2.1.10

In [0]:
print("I am "+20+"years old.")

Memo  
"+" でint型とstr型はつなぐことができない

2.1.11

In [0]:
print("I am "+str(20)+" years old.")

I am 20 years old.


###2.2 変数

2.2.1

In [0]:
a=10
b=a+10
print(b)

20


2.2.2

In [0]:
No.19=10 #エラーとなる

2.2.3

In [0]:
1a=10 #これもエラー

2.2.4

In [0]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


2.2.5

In [0]:
a=10
a=a-3
print(a)

7


Memo  
"=" は「等号」ではなく「代入」

2.2.6

In [0]:
a=10
a-=3
print(a)

7


2.2.7

In [0]:
a=10
a*=2      # a=a*2と同じ意味
print(a)

20


2.2.8

In [0]:
green_apple=100
summer_orange=500
sales_tax=0.1
price=int((green_apple*5+summer_orange*2)*(1.0+sales_tax))
print(price)

1650


###2.3 データ構造

2.3.1

In [0]:
p1=10000    #1月分
p2=20000    #2月分
p3=100000   #3月分
p4=1000     #4月分
p5=200000   #5月分

2.3.2

In [0]:
prices=[10000,20000,100000,1000,200000]
print(type(prices))

<class 'list'>


2.3.3

In [0]:
print(prices[0])
print(prices[4])
print(type(prices[0]))

10000
200000
<class 'int'>


Memo  
リストのインデックスは0から始まる

2.3.4

In [0]:
print(prices[0])
prices[0]=20
print(prices[0])
print(prices)

10000
20
[20, 20000, 100000, 1000, 200000]


2.3.5

In [0]:
print(len(prices))

5


Memo  
len()関数でリストの要素数が取り出せる

2.3.6

In [0]:
string="a new stereophonic sound spectacular"
slist=string.split(" ")
print(string)
print(slist)
print(type(string))
print(type(slist))

a new stereophonic sound spectacular
['a', 'new', 'stereophonic', 'sound', 'spectacular']
<class 'str'>
<class 'list'>


2.3.7

In [0]:
slist=['a','new','stereophonic','sound','spectacular']
string2=" ".join(slist)
print(string2)

a new stereophonic sound spectacular


Memo  
join()メソッド：文字列のリストを結合して一つの文字列にする  
" ".join(string) の形をとる

2.3.8

In [0]:
string="a new stereophonic sound spectacular"
srep=string.replace('s','S')
print(srep)
print(string)

a new Stereophonic Sound Spectacular
a new stereophonic sound spectacular


Memo  
replace()メソッド：文字列の置換
                   元の文字列は変化させない


2.3.9

In [0]:
string="  foo    "  #両端に空白のある文字列
srp=string.strip()
print(srp)

foo


Memo  
strip()メソッド ：文字列の空白を削除する  
lstrip()メソッド：左側の空白を削除  
rstrip()メソッド：右側の空白を削除

2.3.10

In [0]:
prices=[1000,20000,100000,1000,200000]
p1=prices[2:4]　　#リストの3番目(インデックス=2)から4番目(インデックス=3)
p2=prices[2:]     #後ろの値を省略するとここから後ろ全部という意味
p3=prices[:4]　　 #前の値を省略すると最初からという意味
print(p1)
print(p2)
print(p3)

[100000, 1000]
[100000, 1000, 200000]
[1000, 20000, 100000, 1000]


Memo  
スライス機能：複数の要素にアクセスする  
prices[取り出す最初のインデックス値：取り出す最後のインデックス値+1]

2.3.11

In [0]:
prices=[1000,20000,100000,1000,200000]
p1=prices[2:4]
print(p1)
p1[0]="hoge"
print(p1)
print(prices)

[100000, 1000]
['hoge', 1000]
[1000, 20000, 100000, 1000, 200000]


In [0]:
prices=[10,20000,100000,1000,200000]
prices.append(100)
print(prices)

[10, 20000, 100000, 1000, 200000, 100]


Memo  
append()メソッド：要素をリストに追加

Tips 
- ctrl+M+M→コードセルをテキストセルに変換
- ctrl+M+Y→テキストセルをコードセルに変換
- 改行したいときはSpace２回クリック→Enter
- \` で囲ってあげるとhoge→`hoge`になる


2.3.12

In [0]:
humans=['Alice','Mad Hatter','Queen','King']
animals=['Rabbit','Mouse','Puppy','Caterpillar','Cat']
chars=humans+animals
print(chars)

['Alice', 'Mad Hatter', 'Queen', 'King', 'Rabbit', 'Mouse', 'Puppy', 'Caterpillar', 'Cat']


Memo  
リストは+記号で連結できる

2.3.13

In [0]:
prices=[10,20000,100000,1000,200000]
sprices=sorted(prices)
print(sprices)
print(prices)
prices.sort()
print(prices)

[10, 1000, 20000, 100000, 200000]
[10, 20000, 100000, 1000, 200000]
[10, 1000, 20000, 100000, 200000]


Memo  
sorted()関数:  
>小さい順に並び替える  
>大きい順に並び替える場合は`sorted(x,reverse=True)`とする

Tips  
- \>でインデントを追加する　　
- \ で特殊文字を表示する

2.3.14

In [0]:
humans=['Alice','Mad Hatter','Queen','King']
t='Rabbit' in humans
print(t)
s='Rabbit' not in humans
print(s)

False
True


Memo  
in・not in：リストに値があるかを調べる  
>in:リスト内に含まれていれば True  
>not in:リスト内に含まれていなければ True


2.3.15

In [0]:
prices=(1000,20000,100000,1000,200000)
print(type(prices))
print(prices)

<class 'tuple'>
(1000, 20000, 100000, 1000, 200000)


Memo  
タプル：要素を変更できない　　
>タプルは()を使って定義する

2.3.16

In [0]:
prices=(1000,20000,100000,1000,200000)
prices[1]=20  #書き換えようとした
print(prices)

Memo  
[重要] タプルは一度定義すると書き換えることができない

2.3.17

In [0]:
humans=('Alice','Mat Hatter','Queen','king')            #tuple
animals=['Rabbit','Mouse','Puppy','Caterpillar','Cat']  #list
h=list(humans)
print(h)
a=tuple(animals)
print(a)

['Alice', 'Mat Hatter', 'Queen', 'king']
('Rabbit', 'Mouse', 'Puppy', 'Caterpillar', 'Cat')


Memo  
list()関数とtuple()関数を使って互いに変換できる  
関数の引数はタプルで渡され、関数の戻り値として複数の値を返すときや辞書のキーとして使われる

2.3.18

In [0]:
sales={'january':10000,'february':20000,'march':100000,'april':1000,'may':200000}
print(sales['january'])
print(type(sales))

10000
<class 'dict'>


Memo  
辞書は{}を用いて定義する  
型の名前はdict型

2.3.19

In [0]:
sales={'january':10000,'february':20000,'march':100000,'april':1000,'may':200000}
print(sales['january':'april'])  # january-marchまでのデータが欲しい
print(type(sales))

Memo  
[重要]辞書のキーに順番はない  
スライスが使えない

2.3.20

In [0]:
birthday={}
birthday['Alice']='4/1'　  #追加
birthday['Queen']='12/12'　#追加
birthday['King']='7/3'　　 #追加
birthday.pop('Alice')      #削除
print(birthday)

{'Queen': '12/12', 'King': '7/3'}


Memo  
キーと値を追加したり削除したりできる  
pop()メソッド：削除できる

2.3.21

In [0]:
sales={'january':10000,'february':20000,'march':100000,'april':1000,'may':200000}
sales['june']=50000
print(list(sales.items()))

[('january', 10000), ('february', 20000), ('march', 100000), ('april', 1000), ('may', 200000), ('june', 50000)]


Memo  
items()メソッド：すべてのキーと値のペアを取得する  
キーと値はタプル形式で表現される

2.3.22

In [0]:
sales_tokyo={'january':10000,'february':20000,'march':100000,'april':1000,'may':200000}
sales_sapporo=sales_tokyo.copy()
sales_sapporo['january']=5000
print(sales_sapporo)
print(sales_tokyo)

{'january': 5000, 'february': 20000, 'march': 100000, 'april': 1000, 'may': 200000}
{'january': 10000, 'february': 20000, 'march': 100000, 'april': 1000, 'may': 200000}


copy()メソッド：辞書のコピーに用いる  
※＝を用いてもコピーできない

###2.4 基本構文

2.4.1

In [0]:
math=40 #私の数学の得点である
if math>60:
  print("合格")
else:
  print("不合格")

不合格


Memo  
[重要]Pythonではプログラムの構造を示すために空白(インデント)を用いる

In [0]:
if 条件式1:
  処理1
elif 条件式2:
  処理2
elif 条件式3:
  処理3
....
else:
  条件4

2.4.2

In [0]:
humans=['Alice','Mad Hatter','Queen','King']
for h in humans:
  print("名前: "+h)

名前: Alice
名前: Mad Hatter
名前: Queen
名前: King


In [0]:
for 変数 in リスト:
  処理

Memo  
for文のリストのところには、「文字列、タプル、辞書」などを入れることができる

2.4.3

In [0]:
for x in range(5):
  print(x,":",x**2)

0 : 0
1 : 1
2 : 4
3 : 9
4 : 16


Memo  
range()関数：数値の繰り返しができる

2.4.4

In [0]:
humans=['Alice','Mad Hatter','Queen','King']
animals=['Rabbit','Mouse','Puppy','Caterpillar']
for h,a in zip(humans,animals):
  print("human=",h,"\tanimals=",a)

human= Alice 	animals= Rabbit
human= Mad Hatter 	animals= Mouse
human= Queen 	animals= Puppy
human= King 	animals= Caterpillar


Memo  
>zip():複数の配列を同時にfor文でループしたいときに用いる  
>`\t`:タブ記号の出力

2.4.5

In [0]:
humans=['Alice','Mad Hatter','Queen','King']
for i,name in enumerate(humans):
  print(i,name)

0 Alice
1 Mad Hatter
2 Queen
3 King


Memo  
enumerate()関数：リストの値とインデックスを同時に得たいときに用いる

2.4.6

In [0]:
nums=[n for n in range(1,11)]
print(nums)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


2.4.7

In [0]:
nums=[] #空のリストを作成。内包表記では、この中でfor分を回す

2.4.8

In [0]:
nums=[for n in range(1,11)]

2.4.9

In [0]:
nums=[n for n in range(1,11)]
print(nums)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


2.4.10

In [0]:
nums=[n**2+2*n-3 for n in range(1,11)]
print(nums)

[0, 5, 12, 21, 32, 45, 60, 77, 96, 117]


2.4.11

In [0]:
nums=[n**2+2*n-3 for n in range(1,11) if n%2==0]
print(nums)

[5, 21, 45, 77, 117]


Memo  
>複雑な計算式でもOK  
>内包表記の中に条件式も追加できる

###2.5 関数

Memo  
関数の主な目的は何度も呼び出される機能をまとめて再利用すること

2.5.1

In [0]:
def hello_world():
  print("Hello World")

2.5.2

In [0]:
hello_world()

Hello World


2.5.3

In [0]:
def f(x):
  y=2*x
  return y

Memo  
return:関数は数学における関数と同様、パラメータxを受け取ってyを返すことができる
>y=f(x)

2.5.4

In [0]:
def f(x):
  y=2*x
  return y

x_new=5
y_new=f(x_new)
print(y_new)

10


2.5.5

In [0]:
def gree(name,age,birth,animal):
  et=''
  if animal=='nezumi':
    et='ne'
  elif animal=='usagi':
    et='u'
  elif animal=='dragon':
    et='tatsu'
  elif animal=='hebi':
    et='mi'
  elif animal=='inoshishi':
    et='i'
  else:
    et=animal
  prnt='Hello'+name+'('+str(age)+ '),'
  prnt+=birth+' 生まれ. 干支は '+et
  return prnt

g=gree('yamamoto',30,'10/22','inu')
print(g)

Helloyamamoto(30),10/22 生まれ. 干支は inu


2.5.6

In [0]:
g=gree(name=' yamamoto ',age=30,birth='10/22',animal='inu')
print(g)

Hello yamamoto (30),10/22 生まれ. 干支は inu



Memo  
引数名＝値という形式で値を渡すことができる  
→引数の順番を気にする必要が無くなる

2.5.7

In [0]:
def test_func(arr):
  p5=0
  for a in arr:
    if a>5:
      p5=a
      break
  return p5

array=[1,2,6,10]
b=test_func(array)
print(b)

6


2.5.8

In [0]:
def test_func(arr):
  p5=0
  for a in arr:
    if a >5:
      p5=a
      break
  return p5

array=[1,2,6,10]
b=test_func(array)
print(p5) #エラーとなる

Memo  
スコープ
>変数が通用する範囲  
>ローカルスコープの中に存在する変数をローカル変数という  
>一番外側(すべての関数の外)にあるスコープをグローバルスコープという  
>→ここで定義された変数はグローバル変数という  
>グローバルスコープはプログラム内で一つだけ存在する  
>グローバルスコープからはローカル変数を参照することはできない  
>ローカル変数からはグローバル変数を参照できる  


2.5.9

In [0]:
array=[1,2,6,10]
def test_func2():
  p5=0
  for a in array:
    if a > 5:
      p5 = a
      break
  return p5

b=test_func2()
print(b)

6


2.5.10

In [0]:
for i in range(5):
  x=i
  s="foo"

print(x)
print(s)
print(i)

4
foo
4


Memo  
>for文やif文はスコープを作らない

2.5.11

In [0]:
array=[p**2 for p in range(10)]
print(array)
print(p)

Memo  
>内包表記はスコープを作る

2.5.12

In [0]:
animals=['Rabbit','Mouse','Puppy','Caterpillar','Cat']
r=animals.pop()
print(r)
print(animals)

Cat
['Rabbit', 'Mouse', 'Puppy', 'Caterpillar']


Memo  
>クラスは型のこと、メソッドは型を持った変数に紐付けられた関数のこと  
>pop()メソッド：リストから最後の変数を取り出す  
>※pop(x)の場合はリストのインデックスxを取り出す

2.5.13

In [0]:
class Cube:
  def __init__(self,length,width,height):
    self.length=length
    self.width=width
    self.height=height

  def area(self):
    area1=2*(self.length*self.height)
    area2=2*(self.length*self.width)
    area3=2*(self.height*self.width)
    area=area1+area2+area3
    return area
  
  def volume(self):
    vol=self.length*self.height*self.width
    return vol
  
c=Cube(10,20,30)
print("表面積 = ", c.area())
print("体積   = ", c.volume())

表面積 =  2200
体積   =  6000


Memo  
\_\_init__：クラスを宣言した際に自動的に実行される特別なメソッド(コンストラクタ)  
※\_\_init__は\__(2つ)でinitを挟む  
メソッドの最初の引数には自分自身(self)を置くことになっている  
※クラスの１文字目は大文字

###2.6 ライブラリの利用

2.6.1

In [0]:
import math

print(type(math))
print(math)
print(math.pi)
print(math.cos(0))

<class 'module'>
<module 'math' (built-in)>
3.141592653589793
1.0


2.6.2

In [0]:
import numpy as np
npa=np.array([1,2,3])
print(npa)

[1 2 3]


Memo  
パッケージを別名で使用することができる

2.6.3


In [0]:
from math import cos
print(cos(0))

1.0


Memo  
>from パッケージ名 import モジュール名  
>from モジュール名 import 関数名  
などとして必要なものだけ使えるようにすることができる

2.6.4

In [0]:
import math
help(math)

Memo  
help()関数：モジュールの使い方を確認する

2.6.5

In [0]:
import os
print(os.getcwd())
print(os.listdir())
os.chdir("sample_data")
os.mkdir("example")

/content
['.config', 'sample_data']


Memo  
osモジュール：ファイルのディレクトリの操作をpythonプログラムを通じて行うことができる

2.6.6

In [0]:
import datetime
now=datetime.datetime.now()
print(now)
print(type(now))
print(now.year)
print(now.month)
print(now.day)
print(now.hour)
print(now.minute)
print(now.second)
print(now.date())
print(type(now.date()))
print(now.time())
print(type(now.time()))

2020-05-10 12:13:06.425653
<class 'datetime.datetime'>
2020
5
10
12
13
6
2020-05-10
<class 'datetime.date'>
12:13:06.425653
<class 'datetime.time'>


Memo  
datetimeモジュール：pythonで日付や時刻を扱う際に用いる  
>date()メソッド：日付情報のみ  
>time()メソッド：時刻情報のみ

2.6.7

In [0]:
import datetime
today=datetime.date.today()
print(today)
print(type(today))
print(today.year)
print(today.month)
print(today.day)

2020-05-10
<class 'datetime.date'>
2020
5
10


Memo  
>today()関数：本日の日付

2.6.8

In [0]:
import datetime
dtt=datetime.time(hour=16,minute=59,second=30)
print(dtt)
print(type(dtt))

16:59:30
<class 'datetime.time'>


2.6.9

In [0]:
import datetime
now=datetime.datetime.now()
dtdt=datetime.datetime(year=2019,month=11,day=16)
tdelta=now-dtdt
print(tdelta)
print(type(tdelta))
print(tdelta.days)
print(tdelta.total_seconds())


176 days, 12:26:02.168584
<class 'datetime.timedelta'>
176
15251162.168584


Memo  
>timedelta:時間計測の際に使用する

2.6.10

In [0]:
import datetime 
from pytz import timezone
now=datetime.datetime.now(timezone("Asia/Tokyo"))
fmt=now.strftime('%Y-%m-%d (%a) %H:%M:%S')
print(fmt)

2020-05-10 (Sun) 21:40:07


Memo  
>strftime()メソッド：様々なフォーマットの文字列に変換できる

2.6.11

In [0]:
import datetime
s='2020-1-14 17:40'
dtst=datetime.datetime.strptime(s,'%Y-%m-%d %H:%M')
print(dtst)
print(type(dtst))

2020-01-14 17:40:00
<class 'datetime.datetime'>


Memo  
>strptime()メソッド：文字列"s"とその文字列の書式コードを使用

In [0]:
import numpy as np

Memo  
as～という形でパッケージをimportすることで別名でアクセスできる

2.6.12

In [5]:
import numpy as np

lst=[1,3,5,9]
nlist=np.array(lst)

print(type(lst))
print(type(nlist))
print(lst)
print(nlist)

lst0=nlist.tolist()
print(type(lst0))
print(lst0)

<class 'list'>
<class 'numpy.ndarray'>
[1, 3, 5, 9]
[1 3 5 9]
<class 'list'>
[1, 3, 5, 9]


Memo  
Numpy配列はnp.array()関数を用いてリストから作ることができる

2.6.13

In [7]:
import numpy as np

a=np.array([[1,2],[3,4],[5,6],[7,8]])
print(a)
print(a.dtype)
print(a.shape)
print(a.ndim)
print(a.size)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
int64
(4, 2)
2
8


Memo  
>dtypeプロパティ：行列要素の型を示す  
>shapeプロパティ：(行列、列数)のタプルが返ってくる  
>ndimプロパティ：階数(次元数)を返す  
>sizeプロパティ：要素数を返す

2.6.14

In [8]:
import numpy as np

list0=np.zeros(4)
print(list0)

list1=np.ones(5)
print(list1)

list2=np.arange(4)
print(list2)

list3=np.full(4,100)
# list3=np.full(shape=4,fill_value=100)
print(list3)

[0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0 1 2 3]
[100 100 100 100]


Memo  
>np.zeros():初期値要素をすべて0にする  
>np.ones():初期値要素をすべて1にする  
>np.full():初期値要素を任意の値にする

2.6.15

In [9]:
import numpy as np
list0=np.zeros(8)
matrixs0=list0.reshape(2,4)
print(matrixs0)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Memo  
reshape()メソッド：行列の初期化を行う

2.6.16

In [13]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a[1][0])  #要素数へのアクセス
print(a[1,0])   #スライス時のアクセス

4
4


2.6.17

In [12]:
import numpy as np
lst=np.arange(51)

print(lst)
print(lst[-1]) 
print(lst[2:6])
print(lst[40:])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]
50
[2 3 4 5]
[40 41 42 43 44 45 46 47 48 49 50]


2.6.18

In [14]:
import numpy as np
lst=np.arange(15)
print(lst)
dv=lst[2:6]
print(dv)
dv[1]=100
print(dv)
print(lst)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[2 3 4 5]
[  2 100   4   5]
[  0   1   2 100   4   5   6   7   8   9  10  11  12  13  14]


Memo  
Numpy配列では、スライスによって配列はコピーされない  
→スライス上での値変更は元のNumpy配列にも反映される

2.6.19

In [15]:
import numpy as np
lst=np.arange(15)
print(lst)
dv=lst[2:6].copy()  #変更部分
print(dv)
dv[1]=100
print(dv)
print(lst)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[2 3 4 5]
[  2 100   4   5]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


Memo  
copy()メソッド：Numpy配列がコピーされる

2.6.20

In [20]:
import numpy as np
a=np.array([[[1,2,3,4],[4,5,6,7],[3,4,5,6]],\
            [[7,8,9,10],[10,11,12,13],[4,5,6,7]]])
print(a>6)
b=a[a>6]
b[0]=1000
print(b)
print(b.shape)
print(a)

[[[False False False False]
  [False False False  True]
  [False False False False]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [False False False  True]]]
[1000    7    8    9   10   10   11   12   13    7]
(10,)
[[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 3  4  5  6]]

 [[ 7  8  9 10]
  [10 11 12 13]
  [ 4  5  6  7]]]


Memo  
行継続文字：行末におくとその後の改行が無視されて行が継続していると見なされる。  
・バックスラッシュ（\）を使う  
・丸括弧を使う

2.6.21

In [27]:
import numpy as np

av=np.array([1,2,3])
bv=np.array([5,-6,-7])
#足し算及び引き算
cp=av+bv
cm=av-bv
print(cp)
print(cm)
#スカラ-積(ブロ-ドキャスト)
vx=av*bv
print(vx)



[ 6 -4 -4]
[-4  8 10]
[  5 -12 -21]


2.6.22

In [28]:
import numpy as np

av=np.array([1,2,3])
bv=np.array([5,-6,-7])

ip=np.dot(av,bv)
print(ip)

-28


Memo  
np.dot()関数：内積計算を行う

2.6.23